---

- name: Play 1 - Deploy mucho routes to rtr2 and rtr4
  hosts: rtr2,rtr4
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: admin

  tasks:

    - name: Task 1 - Blast Routes
      eos_config:
        src: RouteBlaster.j2

