---

- name: Play 1 - Get Routes and Generate Comparison Output
  hosts: rtr2,rtr4
  vars:
    ansible_user: admin
    ansible_password: admin
    output_path: "{{playbook_dir}}/RouteCompareOutput"
    filename: "{{inventory_hostname}}_allroutes.csv"
  gather_facts: no

  tasks:

    - name: Gather EOS Facts
      eos_facts:

    - name:  Set Date Stamp
      set_fact: date="{{lookup('pipe','date +%Y.%m.%d_%H%m%S')}}"
      run_once: true

    - name: Capture Routes
      eos_command:
        commands:
          - show ip route | json
      register: allroutes

    - name: Create variable from route output
      set_fact:
        vrfdefaultroutes: "{{ allroutes.stdout[0].vrfs.default.routes }}"

    - name: Create rtr2routes variable
      set_fact:
        rtr2routes: "{{ allroutes.stdout[0].vrfs.default.routes | list }}"
      when: ansible_net_hostname == 'rtr2'

    - name: Create rtr4routes variable
      set_fact:
        rtr4routes: "{{ allroutes.stdout[0].vrfs.default.routes | list }}"
      when: ansible_net_hostname == 'rtr4'

    - name: Debug rtr2routes - Kept in Playbook to demo Debug capabilities "The print statement of Ansible :)"
      debug:
        var: rtr2routes

    - name: Remove Output Files if they Exist
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{output_path}}/rtr2_allroutes.csv"
        - "{{output_path}}/rtr4_allroutes.csv"
        - "{{output_path}}/rtr2_uniques.csv"
        - "{{output_path}}/rtr4_uniques.csv"
        - "{{output_path}}/rtr2_commonroutes.csv"
      run_once: true

    - name: Create CSV File, with Headers, for AllRoutes Output
      lineinfile:
        dest: "{{ output_path }}/{{ filename }}"
        line: "Device Name,Route,Next Hop"
        create: yes
        state: present

    - name: Write All Routes to CSV File
      lineinfile:
        dest: "{{ output_path }}/{{ filename }}"
        line: "{{inventory_hostname}},{{item.key}},{{item.value.vias}}"
        create: yes
        state: present
      with_dict: "{{ vrfdefaultroutes }}"

    - name: Create rtr2uniques variable
      set_fact:
        rtr2uniques: "{{ hostvars.rtr2.rtr2routes | difference(hostvars.rtr4.rtr4routes) }}"
      run_once: true
      
    - name: Create rtr4uniques variable
      set_fact:
        rtr4uniques: "{{ hostvars.rtr4.rtr4routes | difference(hostvars.rtr2.rtr2routes) }}"
      run_once: true

    - name: Create rtrcommonroutes variable
      set_fact:
        rtrcommonroutes: "{{ hostvars.rtr2.rtr2routes | intersect(hostvars.rtr4.rtr4routes) }}"
      run_once: true

    - name: Debug rtr2uniques - Kept in Playbook to demo Debug capabilities "The print statement of Ansible :)"
      debug:
        var: rtr2uniques
      run_once: true

    - name: Debug rtr4uniques - Kept in Playbook to demo Debug capabilities "The print statement of Ansible :)"
      debug:
        var: rtr4uniques
      run_once: true

    - name: Create rtr2Uniques CSV File
      lineinfile:
        dest: "{{ output_path }}/rtr2_uniques.csv"
        line: "{{ item }}"
        create: yes
        state: present
      with_items: "{{ rtr2uniques }}"
      run_once: true

    - name: Create rtr4Uniques CSV File
      lineinfile:
        dest: "{{ output_path }}/rtr4_uniques.csv"
        line: "{{ item }}"
        create: yes
        state: present
      with_items: "{{ rtr4uniques }}"
      run_once: true

    - name: Create RTR Common Routes File
      lineinfile:
        dest: "{{ output_path }}/rtr_commonroutes.csv"
        line: "{{ item }}"
        create: yes
        state: present
      with_items: "{{ rtrcommonroutes }}"
      run_once: true
