---

- name: Play 1 - Create List of Static Routes
  hosts: spine1,spine2
  vars:
    output_path: ./RouteCompareOutput
    filename: "{{inventory_hostname}}_Routes.csv"
  gather_facts: no

  tasks:

    - name:  Set Date Stamp
      set_fact: date="{{lookup('pipe','date +%Y.%m.%d_%H%m%S')}}"
      run_once: true

    - name: Capture Routes
      eos_command:
        commands:
          - show ip route | json
      register: allroutes

    - name: Create Dict of vrf default Routes
      set_fact:
        vrfdefaultroutes: "{{ allroutes.stdout[0].vrfs.default.routes }}"

    - name: Create CSV File for Routes
      lineinfile:
        dest: "{{ output_path }}/{{ filename }}"
        line: "Device Name,Route,Next Hop"
        create: yes
        state: present

    - name: Remove Output Files if they Exist
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/arista/ansible/RouteCompare/RouteCompareOutput/spine1_Routes"
        - "/home/arista/ansible/RouteCompare/RouteCompareOutput/spine2_Routes"
      run_once: true

    - name: Write Routes to CSV File
      lineinfile:
        dest: "{{ output_path }}/{{ filename }}"
        line: "{{inventory_hostname}},{{item.key}},{{item.value.vias}}"
        create: yes
        state: present
      with_dict: "{{ vrfdefaultroutes }}"
